---
# TrafficSplit for canary deployments of enrichment service
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: enrichment-service-canary
  namespace: data-processing
spec:
  service: enrichment-service
  backends:
  - service: enrichment-service-stable
    weight: 100
  - service: enrichment-service-canary
    weight: 0

---
apiVersion: v1
kind: Service
metadata:
  name: enrichment-service-stable
  namespace: data-processing
  labels:
    app: enrichment-service
    version: stable
spec:
  selector:
    app: enrichment-service
    version: stable
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: metrics
      port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: enrichment-service-canary
  namespace: data-processing
  labels:
    app: enrichment-service
    version: canary
spec:
  selector:
    app: enrichment-service
    version: canary
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: metrics
      port: 9090
      targetPort: 9090
