---
# TrafficSplit for canary deployments of projection service
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: projection-service-canary
  namespace: data-processing
spec:
  service: projection-service
  backends:
  - service: projection-service-stable
    weight: 100
  - service: projection-service-canary
    weight: 0

---
apiVersion: v1
kind: Service
metadata:
  name: projection-service-stable
  namespace: data-processing
  labels:
    app: projection-service
    version: stable
spec:
  selector:
    app: projection-service
    version: stable
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: metrics
      port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: projection-service-canary
  namespace: data-processing
  labels:
    app: projection-service
    version: canary
spec:
  selector:
    app: projection-service
    version: canary
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: metrics
      port: 9090
      targetPort: 9090
