version: '3.8'

services:
  # Test environment with minimal services
  zookeeper-test:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper-test
    container_name: zookeeper-test
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - test-network

  kafka-test:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka-test
    container_name: kafka-test
    depends_on:
      - zookeeper-test
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-test:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-test:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - test-network

  clickhouse-test:
    image: clickhouse/clickhouse-server:23.8
    hostname: clickhouse-test
    container_name: clickhouse-test
    ports:
      - "8124:8123"
      - "9001:9000"
    environment:
      CLICKHOUSE_DB: data_processing_test
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    networks:
      - test-network

  postgres-test:
    image: postgres:15-alpine
    hostname: postgres-test
    container_name: postgres-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: data_proc_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    networks:
      - test-network

  redis-test:
    image: redis:7-alpine
    hostname: redis-test
    container_name: redis-test
    ports:
      - "6380:6379"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

