{{- if .Values.services.normalization.canary.enabled }}
---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: normalization-service
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: normalization-service
  progressDeadlineSeconds: 600
  service:
    port: 8080
    targetPort: 8080
    portDiscovery: true
  analysis:
    interval: {{ .Values.services.normalization.canary.interval | default "1m" }}
    threshold: {{ .Values.services.normalization.canary.threshold | default 5 }}
    maxWeight: 100
    stepWeight: {{ .Values.services.normalization.canary.stepWeight | default 10 }}
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration-p95
      thresholdRange:
        max: 200
      interval: 1m
    - name: error-rate
      thresholdRange:
        max: 1
      interval: 1m
    webhooks:
    - name: acceptance-test
      type: pre-rollout
      url: http://loadtester.{{ .Release.Namespace }}/
      timeout: 30s
      metadata:
        type: bash
        cmd: "curl -sd 'test' http://normalization-service-canary:8080/health | grep -q 'healthy'"
    - name: load-test
      type: rollout
      url: http://loadtester.{{ .Release.Namespace }}/
      timeout: 5s
      metadata:
        cmd: "hey -z 1m -q 10 -c 2 http://normalization-service-canary:8080/health"
    {{- if .Values.services.normalization.canary.alerts.enabled }}
    - name: slack-notification
      type: event
      url: {{ .Values.services.normalization.canary.alerts.webhookUrl }}
    {{- end }}
{{- end }}
