{{/*
Secret for sensitive configuration
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-processing-pipeline.fullname" . }}-secret
  labels:
    {{- include "data-processing-pipeline.labels" . | nindent 4 }}
type: Opaque
data:
  # Database passwords
  {{- if .Values.externalDependencies.postgresql.password }}
  DATA_PROC_POSTGRES_PASSWORD: {{ .Values.externalDependencies.postgresql.password | b64enc }}
  {{- end }}
  {{- if .Values.externalDependencies.redis.password }}
  DATA_PROC_REDIS_PASSWORD: {{ .Values.externalDependencies.redis.password | b64enc }}
  {{- end }}
  
  # Security secrets
  {{- if .Values.security.jwtSecret }}
  DATA_PROC_JWT_SECRET: {{ .Values.security.jwtSecret | b64enc }}
  {{- end }}
  {{- if .Values.security.encryptionKey }}
  DATA_PROC_ENCRYPTION_KEY: {{ .Values.security.encryptionKey | b64enc }}
  {{- end }}
  
  # API keys
  {{- if .Values.security.apiKeys }}
  {{- range $key, $value := .Values.security.apiKeys }}
  API_KEY_{{ $key | upper }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
  
  # Monitoring secrets
  {{- if .Values.monitoring.grafana.adminPassword }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.monitoring.grafana.adminPassword | b64enc }}
  {{- end }}
  {{- if .Values.monitoring.prometheus.basicAuth }}
  PROMETHEUS_BASIC_AUTH: {{ .Values.monitoring.prometheus.basicAuth | b64enc }}
  {{- end }}
