"""
Curated WECC topology dataset used to hydrate ClickHouse tables and publish topology payloads.

The data is intentionally small but representative so that local development and automated tests
have realistic structures (balancing authorities, zones, nodes, interfaces, etc.) without
depending on private source systems.
"""

WECC_TOPOLOGY_DATA = {
    "balancing_authorities": [
        {
            "ba_id": "CAISO",
            "ba_name": "California Independent System Operator",
            "ba_type": "iso",
            "iso_rto": "CAISO",
            "timezone": "America/Los_Angeles",
            "dst_rules": {
                "observes_dst": True,
                "dst_start_rule": "second Sunday in March",
                "dst_end_rule": "first Sunday in November",
            },
            "load_forecast_zone": "CALIFORNIA",
            "tags": ["california", "iso", "wholesale"],
            "metadata": {
                "region": "CA",
                "operator": "CAISO",
                "website": "https://www.caiso.com",
                "notes": "Sample data set representing CAISO BA footprint.",
            },
        },
        {
            "ba_id": "BPA",
            "ba_name": "Bonneville Power Administration",
            "ba_type": "federal",
            "iso_rto": None,
            "timezone": "America/Los_Angeles",
            "dst_rules": {
                "observes_dst": True,
                "dst_start_rule": "second Sunday in March",
                "dst_end_rule": "first Sunday in November",
            },
            "load_forecast_zone": "PNW",
            "tags": ["pacific_northwest", "hydro"],
            "metadata": {
                "region": "WA-OR-ID",
                "operator": "BPA",
                "website": "https://www.bpa.gov",
                "notes": "Represents BPA balancing authority for sample flows.",
            },
        },
        {
            "ba_id": "BANC",
            "ba_name": "Balancing Authority of Northern California",
            "ba_type": "utility",
            "iso_rto": None,
            "timezone": "America/Los_Angeles",
            "dst_rules": {
                "observes_dst": True,
                "dst_start_rule": "second Sunday in March",
                "dst_end_rule": "first Sunday in November",
            },
            "load_forecast_zone": "NORTHERN_CA",
            "tags": ["northern_california"],
            "metadata": {
                "region": "Northern California",
                "operator": "SMUD (sample)",
                "notes": "Representative BANC footprint to map CAISO exchanges.",
            },
        },
        {
            "ba_id": "LADWP",
            "ba_name": "Los Angeles Department of Water and Power",
            "ba_type": "municipal",
            "iso_rto": None,
            "timezone": "America/Los_Angeles",
            "dst_rules": {
                "observes_dst": True,
                "dst_start_rule": "second Sunday in March",
                "dst_end_rule": "first Sunday in November",
            },
            "load_forecast_zone": "LOS_ANGELES",
            "tags": ["southern_california", "municipal"],
            "metadata": {
                "region": "Los Angeles",
                "load_served_mw": 4500,
                "notes": "Municipal BA embedded within CAISO footprint.",
            },
        },
        {
            "ba_id": "SRP",
            "ba_name": "Salt River Project",
            "ba_type": "utility",
            "iso_rto": None,
            "timezone": "America/Phoenix",
            "dst_rules": {
                "observes_dst": False,
                "dst_start_rule": None,
                "dst_end_rule": None,
            },
            "load_forecast_zone": "ARIZONA_CENTRAL",
            "tags": ["desert_southwest"],
            "metadata": {
                "region": "Arizona",
                "notes": "Used to model Desert Southwest interchange.",
            },
        },
    ],
    "zones": [
        {
            "zone_id": "CAISO_SP15",
            "zone_name": "CAISO SP15",
            "ba_id": "CAISO",
            "zone_type": "load_zone",
            "load_serving_entity": "CAISO",
            "weather_zone": "SP15",
            "peak_demand_mw": 23500.0,
            "planning_area": "Southern California",
            "metadata": {
                "climate_region": "Coastal South",
                "resource_mix": ["gas", "solar", "import"],
            },
        },
        {
            "zone_id": "CAISO_NP15",
            "zone_name": "CAISO NP15",
            "ba_id": "CAISO",
            "zone_type": "load_zone",
            "load_serving_entity": "CAISO",
            "weather_zone": "NP15",
            "peak_demand_mw": 18000.0,
            "planning_area": "Northern California",
            "metadata": {
                "climate_region": "Coastal North",
                "resource_mix": ["gas", "hydro", "import"],
            },
        },
        {
            "zone_id": "BPA_NORTH",
            "zone_name": "BPA North",
            "ba_id": "BPA",
            "zone_type": "generation_zone",
            "load_serving_entity": "BPA",
            "weather_zone": "Columbia Basin",
            "peak_demand_mw": 12000.0,
            "planning_area": "Pacific Northwest",
            "metadata": {"dominant_resource": "hydro"},
        },
        {
            "zone_id": "BANC_VALLEY",
            "zone_name": "BANC Valley",
            "ba_id": "BANC",
            "zone_type": "load_zone",
            "load_serving_entity": "BANC",
            "weather_zone": "Sacramento Valley",
            "peak_demand_mw": 3500.0,
            "planning_area": "Northern California Municipal",
            "metadata": {"notes": "SMUD service territory representation."},
        },
        {
            "zone_id": "SRP_METRO",
            "zone_name": "SRP Metro",
            "ba_id": "SRP",
            "zone_type": "load_zone",
            "load_serving_entity": "SRP",
            "weather_zone": "Phoenix Metro",
            "peak_demand_mw": 7000.0,
            "planning_area": "Arizona",
            "metadata": {"notes": "Used for Desert Southwest interchange modeling."},
        },
    ],
    "nodes": [
        {
            "node_id": "TH_NP15_GEN-APND",
            "node_name": "NP15 Thermal Aggregate",
            "zone_id": "CAISO_NP15",
            "node_type": "generation",
            "voltage_level_kv": 230,
            "latitude": 37.7749,
            "longitude": -122.4194,
            "capacity_mw": 500.0,
            "resource_potential": {
                "technical_potential_mw": 650.0,
                "economic_potential_mw": 550.0,
                "installed_capacity_mw": 480.0,
                "build_limit_mw": 700.0,
                "source": "CAISO PCM Sample 2024",
            },
            "metadata": {"fuel": "natural_gas", "ems_point_id": "NP15-THERM-001"},
        },
        {
            "node_id": "TH_SP15_GEN-APND",
            "node_name": "SP15 Thermal Aggregate",
            "zone_id": "CAISO_SP15",
            "node_type": "generation",
            "voltage_level_kv": 230,
            "latitude": 34.0522,
            "longitude": -118.2437,
            "capacity_mw": 750.0,
            "resource_potential": {
                "technical_potential_mw": 900.0,
                "economic_potential_mw": 820.0,
                "installed_capacity_mw": 760.0,
                "build_limit_mw": 950.0,
                "source": "CAISO PCM Sample 2024",
            },
            "metadata": {"fuel": "natural_gas", "ems_point_id": "SP15-THERM-002"},
        },
        {
            "node_id": "PALOVRDE_2_UNITS",
            "node_name": "Palo Verde Units 1-2",
            "zone_id": "SRP_METRO",
            "node_type": "generation",
            "voltage_level_kv": 500,
            "latitude": 33.3891,
            "longitude": -112.8647,
            "capacity_mw": 1300.0,
            "resource_potential": {
                "technical_potential_mw": 1400.0,
                "economic_potential_mw": 1350.0,
                "installed_capacity_mw": 1310.0,
                "build_limit_mw": 1400.0,
                "source": "SRP Integrated Resource Plan 2023 (sample)",
            },
            "metadata": {"fuel": "nuclear", "ems_point_id": "PV-NUCLEAR-001"},
        },
        {
            "node_id": "MIDWAY_500",
            "node_name": "Midway 500 kV Hub",
            "zone_id": "CAISO_SP15",
            "node_type": "hub",
            "voltage_level_kv": 500,
            "latitude": 35.1234,
            "longitude": -119.4567,
            "capacity_mw": None,
            "resource_potential": {
                "technical_potential_mw": None,
                "economic_potential_mw": None,
                "installed_capacity_mw": None,
                "build_limit_mw": None,
                "source": "Topology reference hub",
            },
            "metadata": {"hub_role": "aggregation", "ems_point_id": "MIDWAY-HUB-500"},
        },
        {
            "node_id": "MALIN500",
            "node_name": "Malin 500",
            "zone_id": "BPA_NORTH",
            "node_type": "intertie",
            "voltage_level_kv": 500,
            "latitude": 41.9922,
            "longitude": -121.4814,
            "capacity_mw": None,
            "resource_potential": {
                "technical_potential_mw": None,
                "economic_potential_mw": None,
                "installed_capacity_mw": None,
                "build_limit_mw": None,
                "source": "Intertie reference hub",
            },
            "metadata": {"hub_role": "intertie", "ems_point_id": "MALIN-INTERTIE-500"},
        },
    ],
    "paths": [
        {
            "path_id": "PATH_15",
            "path_name": "Path 15",
            "from_node": "TH_NP15_GEN-APND",
            "to_node": "TH_SP15_GEN-APND",
            "path_type": "transmission_line",
            "capacity_mw": 5400.0,
            "losses_factor": 0.02,
            "hurdle_rate_usd_per_mwh": 5.50,
            "wheel_rate_usd_per_mwh": 2.25,
            "wecc_path_number": "Path 15",
            "operating_limit_mw": 5000.0,
            "emergency_limit_mw": 5800.0,
            "contingency_limit_mw": 4800.0,
            "metadata": {
                "flowgate_id": "PATH15_FLOWGATE",
                "limiting_element": "Gates #1 500 kV",
                "notes": "North-South transfer constraint across California.",
            },
        },
        {
            "path_id": "PATH_26",
            "path_name": "Path 26",
            "from_node": "TH_SP15_GEN-APND",
            "to_node": "PALOVRDE_2_UNITS",
            "path_type": "transmission_line",
            "capacity_mw": 2800.0,
            "losses_factor": 0.015,
            "hurdle_rate_usd_per_mwh": 3.25,
            "wheel_rate_usd_per_mwh": 1.50,
            "wecc_path_number": "Path 26",
            "operating_limit_mw": 2600.0,
            "emergency_limit_mw": 2900.0,
            "contingency_limit_mw": 2500.0,
            "metadata": {
                "flowgate_id": "PATH26_FLOWGATE",
                "limiting_element": "Midway-Buttonwillow 500 kV",
            },
        },
        {
            "path_id": "PDCI",
            "path_name": "Pacific DC Intertie",
            "from_node": "MALIN500",
            "to_node": "MIDWAY_500",
            "path_type": "intertie",
            "capacity_mw": 3100.0,
            "losses_factor": 0.04,
            "hurdle_rate_usd_per_mwh": 8.75,
            "wheel_rate_usd_per_mwh": None,
            "wecc_path_number": "Path 65",
            "operating_limit_mw": 3100.0,
            "emergency_limit_mw": 3400.0,
            "contingency_limit_mw": 3000.0,
            "metadata": {
                "flowgate_id": "PDCI_FLOWGATE",
                "limiting_element": "Celilo Converter",
                "notes": "Represents the high-voltage DC tie between BPA and CAISO.",
            },
        },
    ],
    "interties": [
        {
            "intertie_id": "CAISO_BPA",
            "intertie_name": "CAISO to BPA Intertie",
            "from_market": "wecc",
            "to_market": "wecc",
            "from_ba": "CAISO",
            "to_ba": "BPA",
            "capacity_mw": 4800.0,
            "atc_ttc_ntc": {"atc_mw": 3200.0, "ttc_mw": 4800.0, "ntc_mw": 3200.0},
            "deliverability_flags": ["firm", "non_firm"],
            "edam_eligible": True,
            "hurdle_rates": {
                "forward_hurdle_usd_per_mwh": 4.0,
                "reverse_hurdle_usd_per_mwh": 3.5,
            },
            "metadata": {
                "scheduling_rights": ["CAISO", "BPA"],
                "loss_adjustment": 0.03,
                "notes": "Sample CAISO ↔ BPA interchange assumptions.",
            },
        },
        {
            "intertie_id": "CAISO_SRP",
            "intertie_name": "CAISO to SRP Intertie",
            "from_market": "wecc",
            "to_market": "wecc",
            "from_ba": "CAISO",
            "to_ba": "SRP",
            "capacity_mw": 2800.0,
            "atc_ttc_ntc": {"atc_mw": 2400.0, "ttc_mw": 2800.0, "ntc_mw": 2400.0},
            "deliverability_flags": ["firm", "conditional"],
            "edam_eligible": False,
            "hurdle_rates": {
                "forward_hurdle_usd_per_mwh": 5.25,
                "reverse_hurdle_usd_per_mwh": 4.75,
            },
            "metadata": {
                "scheduling_rights": ["CAISO", "SRP"],
                "loss_adjustment": 0.028,
            },
        },
    ],
    "hubs": [
        {
            "hub_id": "CAISO_SP15_HUB",
            "hub_name": "CAISO SP15 Hub",
            "zone_id": "CAISO_SP15",
            "hub_type": "pricing_hub",
            "lmp_weighted_nodes": [
                {"node_id": "TH_SP15_GEN-APND", "weight": 0.6},
                {"node_id": "MIDWAY_500", "weight": 0.4},
            ],
            "metadata": {"notes": "Weighted hub basket for SP15 trading."},
        },
        {
            "hub_id": "CAISO_NP15_HUB",
            "hub_name": "CAISO NP15 Hub",
            "zone_id": "CAISO_NP15",
            "hub_type": "pricing_hub",
            "lmp_weighted_nodes": [
                {"node_id": "TH_NP15_GEN-APND", "weight": 0.75},
                {"node_id": "MALIN500", "weight": 0.25},
            ],
            "metadata": {"notes": "Weighted hub basket for NP15 trading."},
        },
    ],
    "interfaces": [
        {
            "interface_id": "CAISO_BANC",
            "interface_name": "CAISO ↔ BANC Market Boundary",
            "interface_type": "ba_interface",
            "from_entity": "CAISO",
            "to_entity": "BANC",
            "directionality": "bi_directional",
            "from_zone": "CAISO_NP15",
            "to_zone": "BANC_VALLEY",
            "flowgate_ids": ["PATH15_FLOWGATE"],
            "transfer_capabilities": {
                "ttc_mw": 3000.0,
                "atc_mw": 2600.0,
                "ntc_mw": 2500.0,
                "firm_ttc_mw": 2200.0,
                "non_firm_ttc_mw": 800.0,
                "import_limit_mw": 2600.0,
                "export_limit_mw": 2400.0,
                "comments": "Sample allocation based on 2023 operations.",
            },
            "loss_factors": {
                "forward_loss_factor": 0.028,
                "reverse_loss_factor": 0.026,
                "loss_calculation_method": "fixed",
                "reference_bus": "MIDWAY_500",
            },
            "hurdle_rates": {
                "forward_hurdle_usd_per_mwh": 4.25,
                "reverse_hurdle_usd_per_mwh": 3.75,
                "wheeling_rate_usd_per_mwh": 2.10,
            },
            "seasonal_variations": [
                {
                    "season": "summer",
                    "start_month": 6,
                    "end_month": 9,
                    "ttc_mw": 2800.0,
                    "atc_mw": 2400.0,
                    "import_limit_mw": 2400.0,
                    "export_limit_mw": 2200.0,
                    "loss_factor": 0.03,
                    "notes": "Higher ambient temperatures reduce import capability.",
                },
                {
                    "season": "winter",
                    "start_month": 11,
                    "end_month": 2,
                    "ttc_mw": 3200.0,
                    "atc_mw": 2800.0,
                    "import_limit_mw": 2800.0,
                    "export_limit_mw": 2600.0,
                    "loss_factor": 0.025,
                    "notes": "Winter path limits reflect hydro-driven conditions.",
                },
            ],
            "operational_constraints": {
                "operating_limit_mw": 2600.0,
                "contingency_limit_mw": 2400.0,
                "remedial_action_scheme": "RAS-15-SAMPLE",
                "must_run_commitment": "Oakland_CT1",
                "comments": "RAS trips import when NP15 voltage instability detected.",
            },
            "regulatory_constraints": {
                "tariff_reference": "BANC OATT Schedule 23",
                "allocation_method": "pro-rata",
                "priority_rights": ["BANC", "CAISO"],
            },
            "edam_participation": {
                "edam_eligible": True,
                "edam_base_schedule": "BANC-EDAM-BASE",
                "edam_transfer_limit_mw": 1800.0,
                "edam_priority": "base_schedule",
                "edam_hurdle_usd_per_mwh": 1.5,
            },
            "metadata": {"source": "Sample 2024 interface assumptions"},
        },
        {
            "interface_id": "CAISO_PNW",
            "interface_name": "CAISO ↔ Pacific Northwest",
            "interface_type": "wecc_path",
            "from_entity": "CAISO",
            "to_entity": "BPA",
            "directionality": "bi_directional",
            "from_zone": "CAISO_NP15",
            "to_zone": "BPA_NORTH",
            "flowgate_ids": ["PDCI_FLOWGATE"],
            "transfer_capabilities": {
                "ttc_mw": 3100.0,
                "atc_mw": 2700.0,
                "ntc_mw": 2700.0,
                "firm_ttc_mw": 2400.0,
                "non_firm_ttc_mw": 700.0,
                "comments": "Representative allocation across PDCI and AC ties.",
            },
            "loss_factors": {
                "forward_loss_factor": 0.035,
                "reverse_loss_factor": 0.033,
                "loss_calculation_method": "piecewise",
                "reference_bus": "MALIN500",
            },
            "hurdle_rates": {
                "forward_hurdle_usd_per_mwh": 6.0,
                "reverse_hurdle_usd_per_mwh": 5.5,
                "wheeling_rate_usd_per_mwh": 2.5,
                "congestion_component_usd_per_mwh": 1.0,
            },
            "seasonal_variations": [
                {
                    "season": "spring",
                    "start_month": 3,
                    "end_month": 5,
                    "ttc_mw": 3300.0,
                    "atc_mw": 2900.0,
                    "loss_factor": 0.032,
                }
            ],
            "operational_constraints": {
                "operating_limit_mw": 3000.0,
                "contingency_limit_mw": 2700.0,
                "remedial_action_scheme": "PDCI_RAS_SAMPLE",
            },
            "regulatory_constraints": {
                "tariff_reference": "CAISO BPM Schedules",
                "allocation_method": "auction",
                "priority_rights": ["CAISO", "BPA"],
            },
            "edam_participation": {
                "edam_eligible": True,
                "edam_transfer_limit_mw": 1500.0,
                "edam_priority": "imbalance",
            },
            "metadata": {"notes": "Combination of PDCI and COI limits for sample data."},
        },
        {
            "interface_id": "CAISO_SOUTHWEST",
            "interface_name": "CAISO ↔ Desert Southwest",
            "interface_type": "transfer_path",
            "from_entity": "CAISO",
            "to_entity": "SRP",
            "directionality": "bi_directional",
            "from_zone": "CAISO_SP15",
            "to_zone": "SRP_METRO",
            "flowgate_ids": ["PATH26_FLOWGATE"],
            "transfer_capabilities": {
                "ttc_mw": 2600.0,
                "atc_mw": 2300.0,
                "ntc_mw": 2200.0,
                "firm_ttc_mw": 2000.0,
                "non_firm_ttc_mw": 600.0,
            },
            "loss_factors": {
                "forward_loss_factor": 0.03,
                "reverse_loss_factor": 0.029,
                "loss_calculation_method": "fixed",
                "reference_bus": "TH_SP15_GEN-APND",
            },
            "hurdle_rates": {
                "forward_hurdle_usd_per_mwh": 4.75,
                "reverse_hurdle_usd_per_mwh": 4.25,
                "wheeling_rate_usd_per_mwh": 1.75,
                "uplift_component_usd_per_mwh": 0.5,
            },
            "seasonal_variations": [
                {
                    "season": "summer",
                    "start_month": 6,
                    "end_month": 9,
                    "ttc_mw": 2400.0,
                    "atc_mw": 2100.0,
                    "loss_factor": 0.031,
                }
            ],
            "operational_constraints": {
                "operating_limit_mw": 2300.0,
                "contingency_limit_mw": 2100.0,
                "remedial_action_scheme": "PATH26_RAS",
            },
            "regulatory_constraints": {
                "tariff_reference": "SRP Transmission Contract (sample)",
                "allocation_method": "rights_based",
                "priority_rights": ["SRP", "CAISO"],
            },
            "edam_participation": {
                "edam_eligible": False,
                "edam_transfer_limit_mw": None,
            },
            "metadata": {"notes": "Represents SW imports via Palo Verde and Eldorado ties."},
        },
    ],
    "wecc_paths": [
        {
            "path_number": "Path 15",
            "path_name": "Midway–Los Banos",
            "path_type": "north_south",
            "from_location": "Midway 500",
            "to_location": "Los Banos 500",
            "rated_mw": 5400.0,
            "operating_mw": 5000.0,
            "emergency_mw": 5800.0,
            "wecc_interfaces": ["CAISO_BANC"],
            "monitored_elements": ["PATH15_FLOWGATE"],
            "controlling_entities": ["CAISO", "BANC"],
            "notes": "CA ISO controlled path connecting northern and southern California.",
        },
        {
            "path_number": "Path 26",
            "path_name": "Midway–Vincent",
            "path_type": "north_south",
            "from_location": "Midway 500",
            "to_location": "Vincent 500",
            "rated_mw": 2800.0,
            "operating_mw": 2600.0,
            "emergency_mw": 2900.0,
            "wecc_interfaces": ["CAISO_SOUTHWEST"],
            "monitored_elements": ["PATH26_FLOWGATE"],
            "controlling_entities": ["CAISO"],
            "notes": "Critical path linking CAISO SP15 and Desert Southwest imports.",
        },
        {
            "path_number": "Path 65",
            "path_name": "Pacific DC Intertie",
            "path_type": "intertie",
            "from_location": "Celilo Converter",
            "to_location": "Sylmar Converter",
            "rated_mw": 3100.0,
            "operating_mw": 3100.0,
            "emergency_mw": 3400.0,
            "wecc_interfaces": ["CAISO_PNW"],
            "monitored_elements": ["PDCI_FLOWGATE"],
            "controlling_entities": ["BPA", "CAISO"],
            "notes": "HVDC tie between BPA and CAISO.",
        },
    ],
    "contract_paths": [
        {
            "contract_path_id": "PDCI_LONG_TERM",
            "contract_path_name": "PDCI Long-Term Rights",
            "source": "BPA",
            "sink": "CAISO",
            "contract_capacity_mw": 1500.0,
            "transmission_owner": "BPA",
            "contract_type": "firm",
            "service_type": "point_to_point",
            "rate_schedule": "BPA-PDCI-23",
            "wheeling_rate_usd_per_mwh": 2.5,
            "loss_factor": 0.035,
            "effective_date": "2024-01-01",
            "termination_date": None,
            "priority_rights": ["CAISO"],
            "notes": "Represents long-term BPA to CAISO transfer rights.",
            "metadata": {"source": "Sample BPA contract data"},
        },
        {
            "contract_path_id": "DESERT_SW_SHORT_TERM",
            "contract_path_name": "Desert Southwest Seasonal Contract",
            "source": "SRP",
            "sink": "CAISO",
            "contract_capacity_mw": 600.0,
            "transmission_owner": "SRP",
            "contract_type": "conditional_firm",
            "service_type": "network",
            "rate_schedule": "SRP-NETWORK-01",
            "wheeling_rate_usd_per_mwh": 3.0,
            "loss_factor": 0.03,
            "effective_date": "2024-06-01",
            "termination_date": "2024-09-30",
            "priority_rights": ["SRP", "CAISO"],
            "notes": "Seasonal import from SRP into CAISO SP15 during summer months.",
            "metadata": {"source": "Sample SRP contract data"},
        },
    ],
}
