apiVersion: apps/v1
kind: Deployment
metadata:
  name: normalize-ticks
  labels:
    app: normalize-ticks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: normalize-ticks
  template:
    metadata:
      labels:
        app: normalize-ticks
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
        linkerd.io/inject: "enabled"
    spec:
      containers:
        - name: normalize-ticks
          image: ghcr.io/254carbon/normalize-ticks:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9090
          envFrom:
            - configMapRef:
                name: normalize-ticks-config
          env:
            - name: DATA_PROC_ENV
              value: "prod"
            - name: DATA_PROC_KAFKA_BOOTSTRAP
              valueFrom:
                secretKeyRef:
                  name: data-processing-kafka
                  key: bootstrap
            - name: DATA_PROC_CLICKHOUSE_URL
              valueFrom:
                secretKeyRef:
                  name: data-processing-clickhouse
                  key: url
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: otel-collector-config
                  key: endpoint
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
