apiVersion: v1
kind: Service
metadata:
  name: normalize-ticks
  labels:
    app: normalize-ticks
spec:
  selector:
    app: normalize-ticks
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 9090
      targetPort: metrics
